spring:
  profiles:
    active: sly

---
spring:
  profiles: sly
  datasource:
    url: jdbc:mysql://localhost:3306/erp_com.cskaoyan?serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13579abc
    type: com.alibaba.druid.pool.DruidDataSource

server:
  servlet:
    context-path: /
  port: 80


---
spring:
  profiles: tangxian
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
server:
  servlet:
    context-path: /
  port: 80

---
spring:
  profiles: xxx
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxx
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
server:
  servlet:
    context-path: /
  port: 80
