server:
  servlet:
    context-path: /admin
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0905iqnd
    url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false

